### ISSUE TITLE
安装npm install和npm run dev的过程出错

### ISSUE THREAD

**Issue by ikokang** [wificoin-project/wwas-admin#10]
npm install 提示错误代码：
root@MyServer:~/wwas-admin# 
npm install
npm ERR! code EINTEGRITY
npm ERR! sha1-eCA6TRwyiuHYbcpkYONptX9AVa4= integrity checksum failed when using sha1: wanted sha1-eCA6TRwyiuHYbcpkYONptX9AVa4= but got sha1-maktZcAnLevoyWtgV7yPv6O+1RE=. (305530 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-22T08_34_41_498Z-debug.log
root@MyServer:~/wwas-admin# npm install
npm ERR! code EINTEGRITY
npm ERR! sha1-eCA6TRwyiuHYbcpkYONptX9AVa4= integrity checksum failed when using sha1: wanted sha1-eCA6TRwyiuHYbcpkYONptX9AVa4= but got sha1-maktZcAnLevoyWtgV7yPv6O+1RE=. (305530 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-22T08_38_39_732Z-debug.log

npm run dev 提示错误代码
root@MyServer:~/wwas-admin# npm run dev

> wwas-admin@1.0.0 dev /root/wwas-admin
> node build/dev-server.js

[HPM] Proxy created: /api  ->  http://wechat.kunteng.org.cn:8001
[HPM] Proxy rewrite rule created: "/api" ~> ""
[HPM] Proxy created: /ms  ->  https://www.easy-mock.com/mock/592501a391470c0ac1fab128
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at Function.listen (/root/wwas-admin/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/root/wwas-admin/build/dev-server.js:71:22)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wwas-admin@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wwas-admin@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-22T08_46_14_375Z-debug.log

我的主机服务器安装了Ubuntu 14 64位和wdcp一键安装包lanmp_v3.2

**Comment by caizhibang** [comment]
已修改，报错误，就把端口号由80修改成其他未被占用的端口号即可。
